engines:
  # Fails locally
  brakeman:
    enabled: false
  bundler-audit:
    enabled: true
  # Fails locally
  csslint:
    enabled: false
  coffeelint:
    enabled: false
  duplication:
    enabled: true
    # Fails with: comparison of Fixnum with String failed
    # config:
    #   languages:
    #     ruby:
    #       mass_threshold: 20
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
  scss-lint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.rb"
  - "**.coffee"
  - "**.js"
  - "**.jsx"
  - "**.css"
  - Gemfile.lock
exclude_paths:
- bin/**/*
- config/**/*
- db/**/*
- features/**/*
- script/**/*
- spec/**/*
- test/**/*
- vendor/**/*
