AllCops:
  TargetRubyVersion: 2.3

Rails:
  Enabled: true

ClassLength:
  Enabled: false

Documentation:
  Enabled: false

LineLength:
  Max: 160

MethodLength:
  Enabled: false

Metrics/AbcSize:
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/ClassLength:
  CountComments: false
  Max: 300

Metrics/ModuleLength:
  CountComments: false
  Max: 300

Rails/FilePath:
  Enabled: false

SingleLineBlockParams:
  Enabled: false

SpaceInsideBrackets:
  Enabled: false

StringLiterals:
  EnforcedStyle: double_quotes

Style/NumericPredicate:
  Enabled: false  

Style/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

Style/VariableNumber:
  Enabled: false
