language: ruby
cache: bundler
script: "bundle exec rake test:ruby && bundle exec rake && bundle exec rake test:acceptance"
before_script:
  - mysql -e 'drop database if exists racing_on_rails_test'
  - bundle exec rake db:setup RAILS_ENV=test

rvm:
  - "2.2.3"

sudo: false
