development:
  adapter: mysql2
  database: racing_on_rails_development
  username: ror_development
  host: localhost
  encoding: utf8

acceptance:
  adapter: mysql2
  database: racing_on_rails_test
  username: ror_test
  host: localhost
  encoding: utf8

test:
  adapter: mysql2
  database: racing_on_rails_test
  username: ror_test
  host: localhost
  encoding: utf8

production:
  adapter: mysql2
  database: racing_on_rails_production
  username: root
  encoding: utf8
  host: localhost
