development:
  adapter: mysql2
  database: racing_on_rails_development_4
  username: ror_development
  host: localhost
  encoding: utf8
  reconnect: false
  pool: 5

acceptance:
  adapter: mysql2
  database: racing_on_rails_test_4
  <% if ENV["TRAVIS"] %>
  username: travis
  <% else %>
  username: ror_test
  <% end %>
  host: localhost
  encoding: utf8
  reconnect: false
  pool: 5

test:
  adapter: mysql2
  database: racing_on_rails_test_4
  <% if ENV["TRAVIS"] %>
  username: travis
  <% else %>
  username: ror_test
  <% end %>
  host: localhost
  encoding: utf8
  reconnect: false
  pool: 5

staging:
  adapter: mysql2
  database: racing_on_rails_staging_4
  username: root
  encoding: utf8
  host: localhost
  reconnect: false
  pool: 5

production:
  adapter: mysql2
  database: racing_on_rails_production_4
  username: root
  encoding: utf8
  host: localhost
  reconnect: false
  pool: 5
