development:
  adapter: mysql2
  database: racing_on_rails_development
  username: ror_development
  host: localhost
  encoding: utf8

acceptance: &acceptance
  adapter: mysql2
  database: racing_on_rails_test
  <% if ENV["TRAVIS"] %>
  username: travis
  <% else %>
  username: ror_test
  <% end %>
  host: localhost
  encoding: utf8

cucumber:
  <<: *acceptance

test:
  adapter: mysql2
  database: racing_on_rails_test<%= ENV["TEST_ENV_NUMBER"] %>
  <% if ENV["TRAVIS"] %>
  username: travis
  <% else %>
  username: ror_test
  <% end %>
  host: localhost
  encoding: utf8
