development:
  elavon:
    login: <%= ENV["ELAVON_LOGIN"] %>
    password: <%= ENV["ELAVON_PASSWORD"] %>
    user: <%= ENV["ELAVON_USER"] %>
  secret_key_base: 06621083e6e8cf3d512820ca88b2a7145fd7d106ef909285b7f49f6fdc04333307fe98a3f503b83a2653218571edf89a370d305385732205781a7a54affb3af7
  stripe:
    login: <%= ENV["STRIPE_LOGIN"] %>
    publishable_key: <%= ENV["STRIPE_PUBISHABLE_KEY"] %>

test:
  elavon:
    login: "unused"
    password: "unused"
    user: "unused"
  secret_key_base: 3f9e912f3e99cb27ee8f70adad18f4d32d68c9815e7d66fb50dc83ed1e801e5d2d99d0f3df562fbb85bfde9516ee1932f1a610691596385332ee7f1f007cbce6
  stripe:
    login: "unused"
    publishable_key: "unused"
