---
# The Skylight ID for the application.
application: 6OB_cBKAWI32

# The authentication token for the application.
authentication: SNuKIWKhDiWSaM/BCm8zNgmfUD468Jg5f1G4/j5ZleJhcHBsaWNhdGlvbl9pZHM9Nk9CX2NCS0FXSTMyJnJvbGU9YWdlbnQ=
